# Generated by Django 2.2.16 on 2021-10-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0028_auto_20211012_2126'),
        ('reviews', '0027_auto_20211013_1503'),
    ]

    operations = [
    ]
